### ISSUE TITLE
Got an exception when set system property startInternalProxy to zap in jnlp file

### ISSUE THREAD

**Issue by dehanw** [AutoGeneral/IridiumApplicationTesting#108]
Please find the log and exception details below. 

And meanwhile, Iridium (1.0.36) could be launched and run successfully via java command line with system property "-DstartInternalProxy=zap".

## **exception**
`ProxyException: An exception was thrown while attempting to configure the proxies
au.com.agic.apptesting.exception.ProxyException: An exception was thrown while attempting to configure the proxies
	at au.com.agic.apptesting.utils.impl.ProxyManagerImpl.configureProxies(ProxyManagerImpl.java:91)
	at au.com.agic.apptesting.TestRunner.run(TestRunner.java:113)
	at au.com.agic.apptesting.Main.run(Main.java:87)
	at au.com.agic.apptesting.Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: au.com.agic.apptesting.exception.ProxyException: java.io.IOException: Could not process the URI jar:https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar!/zap
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.initProxy(ZapProxyUtilsImpl.java:71)
	at au.com.agic.apptesting.utils.impl.ProxyManagerImpl.configureProxies(ProxyManagerImpl.java:54)
	... 12 more
Caused by: java.io.IOException: Could not process the URI jar:https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar!/zap
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$getPath$5(FileSystemUtilsImpl.java:176)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$30/2033519108.apply(Unknown Source)
	at javaslang.control.Try.getOrElseThrow(Try.java:473)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.getPath(FileSystemUtilsImpl.java:176)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.copyFromJar(FileSystemUtilsImpl.java:107)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.startZAPProxy(ZapProxyUtilsImpl.java:128)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.initProxy(ZapProxyUtilsImpl.java:65)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Missing scheme
	at java.nio.file.Paths.get(Unknown Source)
	at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$null$3(FileSystemUtilsImpl.java:172)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$29/1353717832.get(Unknown Source)
	at javaslang.control.Try.of(Try.java:37)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$getPath$4(FileSystemUtilsImpl.java:146)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$28/578680862.get(Unknown Source)
	at javaslang.control.Try.orElse(Try.java:451)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.getPath(FileSystemUtilsImpl.java:146)
	... 16 more

ProxyException: java.io.IOException: Could not process the URI jar:https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar!/zap
au.com.agic.apptesting.exception.ProxyException: java.io.IOException: Could not process the URI jar:https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar!/zap
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.initProxy(ZapProxyUtilsImpl.java:71)
	at au.com.agic.apptesting.utils.impl.ProxyManagerImpl.configureProxies(ProxyManagerImpl.java:54)
	at au.com.agic.apptesting.TestRunner.run(TestRunner.java:113)
	at au.com.agic.apptesting.Main.run(Main.java:87)
	at au.com.agic.apptesting.Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Could not process the URI jar:https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar!/zap
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$getPath$5(FileSystemUtilsImpl.java:176)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$30/2033519108.apply(Unknown Source)
	at javaslang.control.Try.getOrElseThrow(Try.java:473)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.getPath(FileSystemUtilsImpl.java:176)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.copyFromJar(FileSystemUtilsImpl.java:107)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.startZAPProxy(ZapProxyUtilsImpl.java:128)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.initProxy(ZapProxyUtilsImpl.java:65)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Missing scheme
	at java.nio.file.Paths.get(Unknown Source)
	at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$null$3(FileSystemUtilsImpl.java:172)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$29/1353717832.get(Unknown Source)
	at javaslang.control.Try.of(Try.java:37)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$getPath$4(FileSystemUtilsImpl.java:146)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$28/578680862.get(Unknown Source)
	at javaslang.control.Try.orElse(Try.java:451)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.getPath(FileSystemUtilsImpl.java:146)
	... 16 more

IOException: Could not process the URI jar:https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar!/zap
java.io.IOException: Could not process the URI jar:https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar!/zap
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$getPath$5(FileSystemUtilsImpl.java:176)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$30/2033519108.apply(Unknown Source)
	at javaslang.control.Try.getOrElseThrow(Try.java:473)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.getPath(FileSystemUtilsImpl.java:176)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.copyFromJar(FileSystemUtilsImpl.java:107)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.startZAPProxy(ZapProxyUtilsImpl.java:128)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.initProxy(ZapProxyUtilsImpl.java:65)
	at au.com.agic.apptesting.utils.impl.ProxyManagerImpl.configureProxies(ProxyManagerImpl.java:54)
	at au.com.agic.apptesting.TestRunner.run(TestRunner.java:113)
	at au.com.agic.apptesting.Main.run(Main.java:87)
	at au.com.agic.apptesting.Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Missing scheme
	at java.nio.file.Paths.get(Unknown Source)
	at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$null$3(FileSystemUtilsImpl.java:172)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$29/1353717832.get(Unknown Source)
	at javaslang.control.Try.of(Try.java:37)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$getPath$4(FileSystemUtilsImpl.java:146)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$28/578680862.get(Unknown Source)
	at javaslang.control.Try.orElse(Try.java:451)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.getPath(FileSystemUtilsImpl.java:146)
	... 16 more

IllegalArgumentException: Missing scheme
java.lang.IllegalArgumentException: Missing scheme
	at java.nio.file.Paths.get(Unknown Source)
	at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$null$3(FileSystemUtilsImpl.java:172)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$29/1353717832.get(Unknown Source)
	at javaslang.control.Try.of(Try.java:37)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$getPath$4(FileSystemUtilsImpl.java:146)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$28/578680862.get(Unknown Source)
	at javaslang.control.Try.orElse(Try.java:451)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.getPath(FileSystemUtilsImpl.java:146)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.copyFromJar(FileSystemUtilsImpl.java:107)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.startZAPProxy(ZapProxyUtilsImpl.java:128)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.initProxy(ZapProxyUtilsImpl.java:65)
	at au.com.agic.apptesting.utils.impl.ProxyManagerImpl.configureProxies(ProxyManagerImpl.java:54)
	at au.com.agic.apptesting.TestRunner.run(TestRunner.java:113)
	at au.com.agic.apptesting.Main.run(Main.java:87)
	at au.com.agic.apptesting.Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

`

## **log**
`552 javawsApplicationMain INFO - Iridium Build Timestamp: 20170610005135
553 javawsApplicationMain INFO - Downloading JAR file locally for ZAP and Cucumber to use
1115 javawsApplicationMain INFO - Saving driver file geckodriver.exe to C:\Users\dwang\AppData\Local\Temp\driver6004168989255356692geckodriver.exe
1175 javawsApplicationMain INFO - Saving driver file chrome.exe to C:\Users\dwang\AppData\Local\Temp\driver5845359962639380030chrome.exe
1254 javawsApplicationMain INFO - Saving driver file opera.exe to C:\Users\dwang\AppData\Local\Temp\driver329912745175791151opera.exe
1256 javawsApplicationMain INFO - Saving driver file MicrosoftWebDriver.exe to C:\Users\dwang\AppData\Local\Temp\driver7750304528006184965MicrosoftWebDriver.exe
1275 javawsApplicationMain INFO - Saving driver file ie.exe to C:\Users\dwang\AppData\Local\Temp\driver1414850944704392591ie.exe
1404 javawsApplicationMain INFO - Saving driver file phantomjs.exe to C:\Users\dwang\AppData\Local\Temp\driver703234210317445708phantomjs.exe
1405 javawsApplicationMain INFO - WEBAPPTESTER-INFO-0004: System property webdriver.chrome.driver: C:\Users\dwang\AppData\Local\Temp\driver5845359962639380030chrome.exe
1405 javawsApplicationMain INFO - WEBAPPTESTER-INFO-0004: System property webdriver.opera.driver: C:\Users\dwang\AppData\Local\Temp\driver329912745175791151opera.exe
1405 javawsApplicationMain INFO - WEBAPPTESTER-INFO-0004: System property webdriver.ie.driver: C:\Users\dwang\AppData\Local\Temp\driver1414850944704392591ie.exe
1405 javawsApplicationMain INFO - WEBAPPTESTER-INFO-0004: System property phantomjs.binary.path: C:\Users\dwang\AppData\Local\Temp\driver703234210317445708phantomjs.exe
1405 javawsApplicationMain INFO - WEBAPPTESTER-INFO-0004: System property webdriver.gecko.driver: C:\Users\dwang\AppData\Local\Temp\driver6004168989255356692geckodriver.exe
1405 javawsApplicationMain INFO - WEBAPPTESTER-INFO-0004: System property webdriver.edge.driver: C:\Users\dwang\AppData\Local\Temp\driver7750304528006184965MicrosoftWebDriver.exe
1503 javawsApplicationMain ERROR - WEBAPPTESTER-BUG-0007: An exception was raised while attempting to run the Cucumber test scripts
au.com.agic.apptesting.exception.ProxyException: An exception was thrown while attempting to configure the proxies
	at au.com.agic.apptesting.utils.impl.ProxyManagerImpl.configureProxies(ProxyManagerImpl.java:91)
	at au.com.agic.apptesting.TestRunner.run(TestRunner.java:113)
	at au.com.agic.apptesting.Main.run(Main.java:87)
	at au.com.agic.apptesting.Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: au.com.agic.apptesting.exception.ProxyException: java.io.IOException: Could not process the URI jar:https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar!/zap
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.initProxy(ZapProxyUtilsImpl.java:71)
	at au.com.agic.apptesting.utils.impl.ProxyManagerImpl.configureProxies(ProxyManagerImpl.java:54)
	... 12 common frames omitted
Caused by: java.io.IOException: Could not process the URI jar:https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar!/zap
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$getPath$5(FileSystemUtilsImpl.java:176)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$30/2033519108.apply(Unknown Source)
	at javaslang.control.Try.getOrElseThrow(Try.java:473)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.getPath(FileSystemUtilsImpl.java:176)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.copyFromJar(FileSystemUtilsImpl.java:107)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.startZAPProxy(ZapProxyUtilsImpl.java:128)
	at au.com.agic.apptesting.utils.impl.ZapProxyUtilsImpl.initProxy(ZapProxyUtilsImpl.java:65)
	... 13 common frames omitted
Caused by: java.lang.IllegalArgumentException: Missing scheme
	at java.nio.file.Paths.get(Unknown Source)
	at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$null$3(FileSystemUtilsImpl.java:172)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$29/1353717832.get(Unknown Source)
	at javaslang.control.Try.of(Try.java:37)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.lambda$getPath$4(FileSystemUtilsImpl.java:146)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl$$Lambda$28/578680862.get(Unknown Source)
	at javaslang.control.Try.orElse(Try.java:451)
	at au.com.agic.apptesting.utils.impl.FileSystemUtilsImpl.getPath(FileSystemUtilsImpl.java:146)
	... 16 common frames omitted
`

**Comment by mcasperson** [comment]
I'll take a look and see if I can replicate this locally.
