### ISSUE TITLE
focus 'if it exists' throws exception when it doesn't exist

### ISSUE THREAD

**Issue by blahDL** [AutoGeneral/IridiumApplicationTesting#87]
```
au.com.agic.apptesting.exception.WebElementException: All attempts to find element failed
	at au.com.agic.apptesting.utils.impl.SimpleWebElementInteractionImpl.getPresenceElementFoundBy(SimpleWebElementInteractionImpl.java:261)
	at au.com.agic.apptesting.utils.impl.SimpleWebElementInteractionImpl.getPresenceElementFoundBy(SimpleWebElementInteractionImpl.java:223)
	at au.com.agic.apptesting.steps.FocusStepDefinitions.focusElementStep(FocusStepDefinitions.java:60)
	at ✽.And I focus on the element found by alias "BestContactNumber" if it exists(webapptester4914400923408802056.feature:125)
```

**Comment by mcasperson** [comment]
This has been implemented in release 0.0.90.
https://autogeneral.gitbooks.io/iridiumapplicationtesting-gettingstartedguide/content/releases.html
